#> 2002 ----
recoding_educ_2002 <- data.frame(
    old_value = c("No schooling",
"Grade R/0",
"Grade 1/Sub A/Class 1",
"Sub A/Grade 1",
"Grade 2/Sub B/Class 2",
"Sub B/Grade 2",
"Grade 3/Standard 1/ABET/AET 1",
"Grade 3/Standard 1",
"Grade 4/Standard 2",
"Grade 5/Standard 3/ABET/AET 2",
"Grade 5/Standard 3",
"Grade 6/Standard 4",
"Grade 7/Standard 5",
"Grade 7/Standard 5/ABET/AET 3",
"Grade 8/Standard 6/Form 1",
"Grade 9/Standard 7/Form 2",
"Grade 9/Standard 7/Form 2/ABET/AET 4/NCV Level 1/Occupational Certificate-NQF Level 1",
"Grade 10/Standard 8/Form 3/NCV Level 2/Occupational Certificate-NQF Level 2",
"Grade 10/Standard 8/Form 3",
"Grade 11/Standard 9/Form 4",
"Grade 11/Standard 9/Form 4/NCV Level 3/Occupational Certificate-NQF Level 3",
"Grade 12/Standard 10/Form 5/National Senior Certificate/Matric/ NCV Level 4/Occupational Certificate-NQF Level 4",
"Grade 12/Standard 10/Form 5/Matric",
"NTC I",
"NTC l",
"NTC I/N1",
"NTC II",
"NTC II/N2",
"NTC III",
"NTC III/N3",
"N4/NTC 4/Occupational Certificate-NQF Level 5",
"N5/NTC 5/Occupational Certificate-NQF Level 5",
"N6/NTC 6/Occupational Certificate-NQF Level 5",
"Diploma/certificate with less than Grade 12/Std 10",
"Diploma with less than Grade 12/Standard 10",
"Certificate with less than Grade 12/Standard 10",
"Diploma/certificate with Grade 12/Std 10",
"Diploma with Grade 12/Standard 10/Occupational Certificate-NQF Level 6",
"Higher/National/Advance certificate with Grade 12/Std 10/Occupational Certificate-NQF Level 5",
"Higher Diploma/Occupational Certificate (B-Tech Diploma)-NQF Level 7",
"Degree",
"Bachelors Degree/Occupational Certificate-NQF Level 7",
"Postgraduate degree or diploma",
"Honours Degree/Postgraduate Diploma/Occupational Certificate-NQF Level 8",
"Post Higher Diploma (Masters Diploma and Masters Degree)-NQF Level 9",
"Doctoral Degrees (Doctoral Diploma and PhD)-NQF Level 10",
"Other ",
"Don't know",
"Do not know",
"Unspecified"),
    new_value = c("0", "0", "1", "1", "2", "2", "3", "3", "4", "5", "5", "6", "7", "7", "8", "9", "9", "10", "10", "11", "11", "12", "12", "10", "10", "10", "11", "11", "11", "11", "13", "13", "13", "11", "11", "11", "13", "14", "13", "15", "15", "15", "16", "16", "17", "18", "NA", "NA", "NA", "NA")
)

#> 2003 ----
recoding_educ_2003 <- data.frame(
    old_value = c("No schooling",
                  "Grade R/0",
                  "Grade 1/Sub A/Class 1",
                  "Sub A/Grade 1",
                  "Grade 2/Sub B/Class 2",
                  "Sub B/Grade 2",
                  "Grade 3/Standard 1/ABET/AET 1",
                  "Grade 3/Standard 1",
                  "Grade 4/Standard 2",
                  "Grade 5/Standard 3/ABET/AET 2",
                  "Grade 5/Standard 3",
                  "Grade 6/Standard 4",
                  "Grade 7/Standard 5",
                  "Grade 7/Standard 5/ABET/AET 3",
                  "Grade 8/Standard 6/Form 1",
                  "Grade 9/Standard 7/Form 2",
                  "Grade 9/Standard 7/Form 2/ABET/AET 4/NCV Level 1/Occupational Certificate-NQF Level 1",
                  "Grade 10/Standard 8/Form 3/NCV Level 2/Occupational Certificate-NQF Level 2",
                  "Grade 10/Standard 8/Form 3",
                  "Grade 11/Standard 9/Form 4",
                  "Grade 11/Standard 9/Form 4/NCV Level 3/Occupational Certificate-NQF Level 3",
                  "Grade 12/Standard 10/Form 5/National Senior Certificate/Matric/ NCV Level 4/Occupational Certificate-NQF Level 4",
                  "Grade 12/Standard 10/Form 5/Matric",
                  "NTC I",
                  "NTC l",
                  "NTC I/N1",
                  "NTC II",
                  "NTC II/N2",
                  "NTC III",
                  "NTC III/N3",
                  "N4/NTC 4/Occupational Certificate-NQF Level 5",
                  "N5/NTC 5/Occupational Certificate-NQF Level 5",
                  "N6/NTC 6/Occupational Certificate-NQF Level 5",
                  "Diploma/certificate with less than Grade 12/Std 10",
                  "Diploma with less than Grade 12/Standard 10",
                  "Diploma/Certificate with less than grade 12/STD 10 ",
                  "Certificate with less than Grade 12/Standard 10",
                  "Diploma/certificate with Grade 12/Std 10",
                  "Diploma/Certificate with grade 12/STD 10",
                  "Diploma with Grade 12/Standard 10/Occupational Certificate-NQF Level 6",
                  "Higher/National/Advance certificate with Grade 12/Std 10/Occupational Certificate-NQF Level 5",
                  "Higher Diploma/Occupational Certificate (B-Tech Diploma)-NQF Level 7",
                  "Degree",
                  "Bachelors Degree/Occupational Certificate-NQF Level 7",
                  "Postgraduate degree or diploma",
                  "Honours Degree/Postgraduate Diploma/Occupational Certificate-NQF Level 8",
                  "Post Higher Diploma (Masters Diploma and Masters Degree)-NQF Level 9",
                  "Doctoral Degrees (Doctoral Diploma and PhD)-NQF Level 10",
                  "Other",
                  "Other ",
                  "Don't know",
                  "Do not know",
                  "Unspecified"),
    new_value = c("0",
                  "0",
                  "1",
                  "1",
                  "2",
                  "2",
                  "3",
                  "3",
                  "4",
                  "5",
                  "5",
                  "6",
                  "7",
                  "7",
                  "8",
                  "9",
                  "9",
                  "10",
                  "10",
                  "11",
                  "11",
                  "12",
                  "12",
                  "10",
                  "10",
                  "10",
                  "11",
                  "11",
                  "11",
                  "11",
                  "13",
                  "13",
                  "13",
                  "11",
                  "11",
                  "11",
                  "11",
                  "13",
                  "13",
                  "14",
                  "13",
                  "15",
                  "15",
                  "15",
                  "16",
                  "16",
                  "17",
                  "18",
                  "NA",
                  "NA",
                  "NA",
                  "NA",
                  "NA")
)

#> 2004 ----
recoding_educ_2004 <- data.frame(
    old_value = c("No schooling",
                  "Grade R/0",
                  "Grade 1/Sub A/Class 1",
                  "Sub A/Grade 1",
                  "Grade 2/Sub B/Class 2",
                  "Sub B/Grade 2",
                  "Grade 3/Standard 1/ABET/AET 1",
                  "Grade 3/Standard 1",
                  "Grade 4/Standard 2",
                  "Grade 5/Standard 3/ABET/AET 2",
                  "Grade 5/Standard 3",
                  "Grade 6/Standard 4",
                  "Grade 7/Standard 5",
                  "Grade 7/Standard 5/ABET/AET 3",
                  "Grade 8/Standard 6/Form 1",
                  "Grade 9/Standard 7/Form 2",
                  "Grade 9/Standard 7/Form 2/ABET/AET 4/NCV Level 1/Occupational Certificate-NQF Level 1",
                  "Grade 10/Standard 8/Form 3/NCV Level 2/Occupational Certificate-NQF Level 2",
                  "Grade 10/Standard 8/Form 3",
                  "Grade 11/Standard 9/Form 4",
                  "Grade 11/Standard 9/Form 4/NCV Level 3/Occupational Certificate-NQF Level 3",
                  "Grade 12/Standard 10/Form 5/National Senior Certificate/Matric/ NCV Level 4/Occupational Certificate-NQF Level 4",
                  "Grade 12/Standard 10/Form 5/Matric",
                  "NTC I",
                  "NTC l",
                  "NTC I/N1",
                  "NTC II",
                  "NTC II/N2",
                  "NTC III",
                  "NTC III/N3",
                  "N4/NTC 4/Occupational Certificate-NQF Level 5",
                  "N5/NTC 5/Occupational Certificate-NQF Level 5",
                  "N6/NTC 6/Occupational Certificate-NQF Level 5",
                  "Diploma/certificate with less than Grade 12/Std 10",
                  "Diploma with less than Grade 12/Standard 10",
                  "Diploma/Certificate with less than grade 12/STD 10 ",
                  "Certificate with less than Grade 12/Standard 10",
                  "Diploma/certificate with Grade 12/Std 10",
                  "Diploma/Certificate with grade 12/STD 10",
                  "Diploma with Grade 12/Standard 10/Occupational Certificate-NQF Level 6",
                  "Higher/National/Advance certificate with Grade 12/Std 10/Occupational Certificate-NQF Level 5",
                  "Higher Diploma/Occupational Certificate (B-Tech Diploma)-NQF Level 7",
                  "Degree",
                  "Bachelors Degree/Occupational Certificate-NQF Level 7",
                  "Postgraduate degree or diploma",
                  "Honours Degree/Postgraduate Diploma/Occupational Certificate-NQF Level 8",
                  "Post Higher Diploma (Masters Diploma and Masters Degree)-NQF Level 9",
                  "Doctoral Degrees (Doctoral Diploma and PhD)-NQF Level 10",
                  "Other",
                  "Other ",
                  "Don't know",
                  "Do not know",
                  "Unspecified",
                  "Grade 7 / Standard 5",
                  "Grade 8 / Standard 6 / Form 1",
                  "Grade 10 / Standard 8 / Form 3",
                  "Grade 12 / Standard 10 / Form 5 / Matric",
                  "Grade 11 / Standard 9 / Form 4",
                  "Honors Degree",
                  "Higher Degree ( Masters, Doctorate)",
                  "Certificate with Grade 12 / Std 10",
                  "Grade 5 / Standard 3",
                  "Bachelors Degree",
                  "Bachelors Degree and Diploma",
                  "Grade 9 / Standard 7 / Form 2",
                  "Grade 6 / Standard 4",
                  "Grade 2 / Sub B",
                  "Grade 3 / Standard 1",
                  "Grade 4 / Standard 2",
                  "Diploma with Grade 12 / Std 10",
                  "Diploma with less than Grade 12 / Std 10",
                  "Certificate with less than Grade 12 / Std 10",
                  "Grade 1 / Sub A"),
    new_value = c("0",
                  "0",
                  "1",
                  "1",
                  "2",
                  "2",
                  "3",
                  "3",
                  "4",
                  "5",
                  "5",
                  "6",
                  "7",
                  "7",
                  "8",
                  "9",
                  "9",
                  "10",
                  "10",
                  "11",
                  "11",
                  "12",
                  "12",
                  "10",
                  "10",
                  "10",
                  "11",
                  "11",
                  "11",
                  "11",
                  "13",
                  "13",
                  "13",
                  "11",
                  "11",
                  "11",
                  "11",
                  "13",
                  "13",
                  "14",
                  "13",
                  "15",
                  "15",
                  "15",
                  "16",
                  "16",
                  "17",
                  "18",
                  "NA",
                  "NA",
                  "NA",
                  "NA",
                  "NA",
                  "7",
                  "8",
                  "10",
                  "12",
                  "11",
                  "16",
                  "18",
                  "13",
                  "5",
                  "15",
                  "16",
                  "9",
                  "6",
                  "2",
                  "3",
                  "4",
                  "13",
                  "11",
                  "11",
                  "1")
)

#> 2005 ----
recoding_educ_2005 <- data.frame(
    old_value = c("No schooling",
                  "Grade R / 0",
                  "Grade 1/Sub A/Class 1",
                  "Sub A/Grade 1",
                  "Grade 1 / Sub A",
                  "Grade 2/Sub B/Class 2",
                  "Sub B/Grade 2",
                  "Grade 2 / Sub B",
                  "Grade 3/Standard 1/ABET/AET 1",
                  "Grade 3 / Standard 1",
                  "Grade 4 / Standard 2",
                  "Grade 5/Standard 3/ABET/AET 2",
                  "Grade 5 / Standard 3",
                  "Grade 6 / Standard 4",
                  "Grade 7 / Standard 5",
                  "Grade 7/Standard 5/ABET/AET 3",
                  "Grade 8 / Standard 6 / Form 1",
                  "Grade 9 / Standard 7 / Form 2",
                  "Grade 9/Standard 7/Form 2/ABET/AET 4/NCV Level 1/Occupational Certificate-NQF Level 1",
                  "Grade 10/Standard 8/Form 3/NCV Level 2/Occupational Certificate-NQF Level 2",
                  "Grade 10 / Standard 8 / Form 3",
                  "Grade 11 / Standard 9 / Form 4",
                  "Grade 11/Standard 9/Form 4/NCV Level 3/Occupational Certificate-NQF Level 3",
                  "Grade 12/Standard 10/Form 5/National Senior Certificate/Matric/ NCV Level 4/Occupational Certificate-NQF Level 4",
                  "Grade 12 / Standard 10 / Form 5/Matric",
                  "NTC I",
                  "NTC l",
                  "NTC I/N1",
                  "NTC II",
                  "NTC II/N2",
                  "NTC III",
                  "NTC III/N3",
                  "N4/NTC 4/Occupational Certificate-NQF Level 5",
                  "N5/NTC 5/Occupational Certificate-NQF Level 5",
                  "N6/NTC 6/Occupational Certificate-NQF Level 5",
                  "Diploma/certificate with less than Grade 12/Std 10",
                  "Diploma with less than Grade 12 / Std 10",
                  "Diploma with less than Grade 12/Standard 10",
                  "Certificate with less than Grade 12/Standard 10",
                  "Diploma/certificate with Grade 12/Std 10",
                  "Certificate with Grade 12 / Std 10",
                  "Diploma with Grade 12 / Std 10",
                  "Diploma with Grade 12/Standard 10/Occupational Certificate-NQF Level 6",
                  "Higher/National/Advance certificate with Grade 12/Std 10/Occupational Certificate-NQF Level 5",
                  "Higher Diploma/Occupational Certificate (B-Tech Diploma)-NQF Level 7",
                  "Degree",
                  "Bachelors Degree/Occupational Certificate-NQF Level 7",
                  "Postgraduate degree or diploma",
                  "Honours Degree/Postgraduate Diploma/Occupational Certificate-NQF Level 8",
                  "Post Higher Diploma (Masters Diploma and Masters Degree)-NQF Level 9",
                  "Doctoral Degrees (Doctoral Diploma and PhD)-NQF Level 10",
                  "Other",
                  "Don't know",
                  "Do not know",
                  "Unspecified",
                  "Honours Degree",
                  "Certificate with less than grade 12/STD 10",
                  "Bachelors Degree",
                  "Bachelors Degree and Diploma",
                  "Higher Degree (Masters, Doctorate)",
                  "Diploma with less than grade 12 / STD 10",
                  "Diploma / certificate with less than Grade 12 / Std 10",
                  "Certificate with grade 12 / STD 10",
                  "Diploma with grade 12 / STD 10"),
    new_value = c("0",
                  "0",
                  "1",
                  "1",
                  "1",
                  "2",
                  "2",
                  "2",
                  "3",
                  "3",
                  "4",
                  "5",
                  "5",
                  "6",
                  "7",
                  "7",
                  "8",
                  "9",
                  "9",
                  "10",
                  "10",
                  "11",
                  "11",
                  "12",
                  "12",
                  "10",
                  "10",
                  "10",
                  "11",
                  "11",
                  "11",
                  "11",
                  "13",
                  "13",
                  "13",
                  "11",
                  "11",
                  "11",
                  "11",
                  "13",
                  "13",
                  "12",
                  "14",
                  "13",
                  "15",
                  "15",
                  "15",
                  "16",
                  "16",
                  "17",
                  "18",
                  "NA",
                  "NA",
                  "NA",
                  "NA",
                  "16",
                  "11",
                  "15",
                  "16",
                  "17",
                  "11",
                  "11",
                  "13",
                  "13")
)


#> 2006 ----
recoding_educ_2006 <- data.frame(
    old_value = c("No schooling",
                  "Grade R / 0",
                  "Grade 1/Sub A/Class 1",
                  "Sub A/Grade 1",
                  "Grade 1 / Sub A",
                  "Grade 2/Sub B/Class 2",
                  "Sub B/Grade 2",
                  "Grade 2 / Sub B",
                  "Grade 3/Standard 1/ABET/AET 1",
                  "Grade 3 / Standard 1",
                  "Grade 4 / Standard 2",
                  "Grade 5/Standard 3/ABET/AET 2",
                  "Grade 5 / Standard 3",
                  "Grade 6 / Standard 4",
                  "Grade 7 / Standard 5",
                  "Grade 7/Standard 5/ABET/AET 3",
                  "Grade 8 / Standard 6 / Form 1",
                  "Grade 9 / Standard 7 / Form 2",
                  "Grade 9/Standard 7/Form 2/ABET/AET 4/NCV Level 1/Occupational Certificate-NQF Level 1",
                  "Grade 10/Standard 8/Form 3/NCV Level 2/Occupational Certificate-NQF Level 2",
                  "Grade 10 / Standard 8 / Form 3",
                  "Grade 11 / Standard 9 / Form 4",
                  "Grade 11/Standard 9/Form 4/NCV Level 3/Occupational Certificate-NQF Level 3",
                  "Grade 12/Standard 10/Form 5/National Senior Certificate/Matric/ NCV Level 4/Occupational Certificate-NQF Level 4",
                  "Grade 12 / Standard 10 / Form 5/Matric",
                  "NTC I",
                  "NTC l",
                  "NTC I/N1",
                  "NTC II",
                  "NTC II/N2",
                  "NTC III",
                  "NTC III/N3",
                  "N4/NTC 4/Occupational Certificate-NQF Level 5",
                  "N5/NTC 5/Occupational Certificate-NQF Level 5",
                  "N6/NTC 6/Occupational Certificate-NQF Level 5",
                  "Diploma/certificate with less than Grade 12/Std 10",
                  "Diploma with less than Grade 12 / Std 10",
                  "Diploma with less than Grade 12/Standard 10",
                  "Certificate with less than Grade 12/Standard 10",
                  "Diploma/certificate with Grade 12/Std 10",
                  "Certificate with Grade 12 / Std 10",
                  "Diploma with Grade 12 / Std 10",
                  "Diploma with Grade 12/Standard 10/Occupational Certificate-NQF Level 6",
                  "Higher/National/Advance certificate with Grade 12/Std 10/Occupational Certificate-NQF Level 5",
                  "Higher Diploma/Occupational Certificate (B-Tech Diploma)-NQF Level 7",
                  "Degree",
                  "Bachelors Degree/Occupational Certificate-NQF Level 7",
                  "Postgraduate degree or diploma",
                  "Honours Degree/Postgraduate Diploma/Occupational Certificate-NQF Level 8",
                  "Post Higher Diploma (Masters Diploma and Masters Degree)-NQF Level 9",
                  "Doctoral Degrees (Doctoral Diploma and PhD)-NQF Level 10",
                  "Other",
                  "Don't know",
                  "Do not know",
                  "Unspecified",
                  "Honours Degree",
                  "Certificate with less than grade 12/STD 10",
                  "Bachelors Degree",
                  "Bachelors Degree and Diploma",
                  "Higher Degree (Masters, Doctorate)",
                  "Diploma with less than grade 12 / STD 10",
                  "Diploma / certificate with less than Grade 12 / Std 10",
                  "Certificate with grade 12 / STD 10",
                  "Diploma with grade 12 / STD 10",
                  "Grade 7/Standard 5",
                  "Grade 8/Standard 6/Form 1",
                  "Grade 12/Standard 10/Form 5/Matric",
                  "Grade 10/Standard 8/Form 3",
                  "Grade 9/Standard 7/Form 2",
                  "Grade 6/Standard 4",
                  "Grade 11/Standard 9/Form 4",
                  "Diploma with grade 12/STD 10",
                  "Grade 3/Standard 1",
                  "Grade 4/Standard 2",
                  "Grade R/0",
                  "Grade 5/Standard 3",
                  "Bachelor's Degree and Diploma",
                  "Bachelor's Degree",
                  "Certificate with grade 12/STD 10",
                  "Diploma with less than grade 12/STD 10"),
    new_value = c("0",
                  "0",
                  "1",
                  "1",
                  "1",
                  "2",
                  "2",
                  "2",
                  "3",
                  "3",
                  "4",
                  "5",
                  "5",
                  "6",
                  "7",
                  "7",
                  "8",
                  "9",
                  "9",
                  "10",
                  "10",
                  "11",
                  "11",
                  "12",
                  "12",
                  "10",
                  "10",
                  "10",
                  "11",
                  "11",
                  "11",
                  "11",
                  "13",
                  "13",
                  "13",
                  "11",
                  "11",
                  "11",
                  "11",
                  "13",
                  "13",
                  "12",
                  "14",
                  "13",
                  "15",
                  "15",
                  "15",
                  "16",
                  "16",
                  "17",
                  "18",
                  "NA",
                  "NA",
                  "NA",
                  "NA",
                  "16",
                  "11",
                  "15",
                  "16",
                  "17",
                  "11",
                  "11",
                  "13",
                  "13",
                  "7",
                  "8",
                  "12",
                  "10",
                  "9",
                  "6",
                  "11",
                  "13",
                  "3",
                  "4",
                  "0",
                  "5",
                  "16",
                  "15",
                  "13",
                  "11")
)

#> 2007 ----

recoding_educ_2007 <- data.frame(
    old_value = c("No schooling", "Grade R / 0", "Grade 1/Sub A/Class 1", "Sub A/Grade 1", "Grade 1 / Sub A", "Grade 2/Sub B/Class 2", "Sub B/Grade 2", "Grade 2 / Sub B", "Grade 3/Standard 1/ABET/AET 1", "Grade 3 / Standard 1", "Grade 4 / Standard 2", "Grade 5/Standard 3/ABET/AET 2", "Grade 5 / Standard 3", "Grade 6 / Standard 4", "Grade 7 / Standard 5", "Grade 7/Standard 5/ABET/AET 3", "Grade 8 / Standard 6 / Form 1", "Grade 9 / Standard 7 / Form 2", "Grade 9/Standard 7/Form 2/ABET/AET 4/NCV Level 1/Occupational Certificate-NQF Level 1", "Grade 10/Standard 8/Form 3/NCV Level 2/Occupational Certificate-NQF Level 2", "Grade 10 / Standard 8 / Form 3", "Grade 11 / Standard 9 / Form 4", "Grade 11/Standard 9/Form 4/NCV Level 3/Occupational Certificate-NQF Level 3", "Grade 12/Standard 10/Form 5/National Senior Certificate/Matric/ NCV Level 4/Occupational Certificate-NQF Level 4", "Grade 12 / Standard 10 / Form 5/Matric", "NTC I", "NTC l", "NTC I/N1", "NTC II", "NTC II/N2", "NTC III", "NTC III/N3", "N4/NTC 4/Occupational Certificate-NQF Level 5", "N5/NTC 5/Occupational Certificate-NQF Level 5", "N6/NTC 6/Occupational Certificate-NQF Level 5", "Diploma/certificate with less than Grade 12/Std 10", "Diploma with less than Grade 12 / Std 10", "Diploma with less than Grade 12/Standard 10", "Certificate with less than Grade 12/Standard 10", "Diploma/certificate with Grade 12/Std 10", "Certificate with Grade 12 / Std 10", "Diploma with Grade 12 / Std 10", "Diploma with Grade 12/Standard 10/Occupational Certificate-NQF Level 6", "Higher/National/Advance certificate with Grade 12/Std 10/Occupational Certificate-NQF Level 5", "Higher Diploma/Occupational Certificate (B-Tech Diploma)-NQF Level 7", "Degree", "Bachelors Degree/Occupational Certificate-NQF Level 7", "Postgraduate degree or diploma", "Honours Degree/Postgraduate Diploma/Occupational Certificate-NQF Level 8", "Post Higher Diploma (Masters Diploma and Masters Degree)-NQF Level 9", "Doctoral Degrees (Doctoral Diploma and PhD)-NQF Level 10", "Other", "Don't know", "Do not know", "Unspecified", "Honours Degree", "Certificate with less than grade 12/STD 10", "Bachelors Degree", "Bachelors Degree and Diploma", "Higher Degree (Masters, Doctorate)", "Diploma with less than grade 12 / STD 10", "Diploma / certificate with less than Grade 12 / Std 10", "Certificate with grade 12 / STD 10", "Diploma with grade 12 / STD 10", "Grade 7/Standard 5", "Grade 12/Standard 10/Form 5/Matric", "Grade 8/Standard 6/Form 1", "Grade 9/Standard 7/Form 2", "Diploma with grade 12/STD 10", "Grade 6/Standard 4", "Certificate with grade 12/STD 10", "Grade 10/Standard 8/Form 3", "Grade 3/Standard 1", "Grade 4/Standard 2", "Grade 11/Standard 9/Form 4", "Grade 5/Standard 3", "Diploma with less than grade 12/STD 10", "Bachelor's Degree", "Bachelor's Degree and Diploma", "Grade R/0"),
    new_value = c("0", "0", "1", "1", "1", "2", "2", "2", "3", "3", "4", "5", "5", "6", "7", "7", "8", "9", "9", "10", "10", "11", "11", "12", "12", "10", "10", "10", "11", "11", "11", "11", "13", "13", "13", "11", "11", "11", "11", "13", "13", "12", "14", "13", "15", "15", "15", "16", "16", "17", "18", "NA", "NA", "NA", "NA", "16", "11", "15", "16", "17", "11", "11", "13", "13", "7", "12", "8", "9", "13", "6", "13", "10", "3", "4", "11", "5", "11", "15", "16", "0")
)

#> 2008 ----

recoding_educ_2008 <- data.frame(
    old_value = c("No schooling", "Grade R / 0", "Grade 1/Sub A/Class 1", "Sub A/Grade 1", "Grade 1 / Sub A", "Grade 2/Sub B/Class 2", "Sub B/Grade 2", "Grade 2 / Sub B", "Grade 3/Standard 1/ABET/AET 1", "Grade 3 / Standard 1", "Grade 4 / Standard 2", "Grade 5/Standard 3/ABET/AET 2", "Grade 5 / Standard 3", "Grade 6 / Standard 4", "Grade 7 / Standard 5", "Grade 7/Standard 5/ABET/AET 3", "Grade 8 / Standard 6 / Form 1", "Grade 9 / Standard 7 / Form 2", "Grade 9/Standard 7/Form 2/ABET/AET 4/NCV Level 1/Occupational Certificate-NQF Level 1", "Grade 10/Standard 8/Form 3/NCV Level 2/Occupational Certificate-NQF Level 2", "Grade 10 / Standard 8 / Form 3", "Grade 11 / Standard 9 / Form 4", "Grade 11/Standard 9/Form 4/NCV Level 3/Occupational Certificate-NQF Level 3", "Grade 12/Standard 10/Form 5/National Senior Certificate/Matric/ NCV Level 4/Occupational Certificate-NQF Level 4", "Grade 12 / Standard 10 / Form 5/Matric", "NTC I", "NTC l", "NTC I/N1", "NTC II", "NTC II/N2", "NTC III", "NTC III/N3", "N4/NTC 4/Occupational Certificate-NQF Level 5", "N5/NTC 5/Occupational Certificate-NQF Level 5", "N6/NTC 6/Occupational Certificate-NQF Level 5", "Diploma/certificate with less than Grade 12/Std 10", "Diploma with less than Grade 12 / Std 10", "Diploma with less than Grade 12/Standard 10", "Certificate with less than Grade 12/Standard 10", "Diploma/certificate with Grade 12/Std 10", "Certificate with Grade 12 / Std 10", "Diploma with Grade 12 / Std 10", "Diploma with Grade 12/Standard 10/Occupational Certificate-NQF Level 6", "Higher/National/Advance certificate with Grade 12/Std 10/Occupational Certificate-NQF Level 5", "Higher Diploma/Occupational Certificate (B-Tech Diploma)-NQF Level 7", "Degree", "Bachelors Degree/Occupational Certificate-NQF Level 7", "Postgraduate degree or diploma", "Honours Degree/Postgraduate Diploma/Occupational Certificate-NQF Level 8", "Post Higher Diploma (Masters Diploma and Masters Degree)-NQF Level 9", "Doctoral Degrees (Doctoral Diploma and PhD)-NQF Level 10", "Other", "Don't know", "Do not know", "Unspecified", "Honours Degree", "Certificate with less than grade 12/STD 10", "Bachelors Degree", "Bachelors Degree and Diploma", "Higher Degree (Masters, Doctorate)", "Diploma with less than grade 12 / STD 10", "Diploma / certificate with less than Grade 12 / Std 10", "Certificate with grade 12 / STD 10", "Diploma with grade 12 / STD 10", "Grade 7/Standard 5", "Grade 12/Standard 10/Form 5/Matric", "Grade 8/Standard 6/Form 1", "Grade 9/Standard 7/Form 2", "Diploma with grade 12/STD 10", "Grade 6/Standard 4", "Certificate with grade 12/STD 10", "Grade 10/Standard 8/Form 3", "Grade 3/Standard 1", "Grade 4/Standard 2", "Grade 11/Standard 9/Form 4", "Grade 5/Standard 3", "Diploma with less than grade 12/STD 10", "Bachelor's Degree", "Bachelor's Degree and Diploma", "Grade R/0"),
    new_value = c("0", "0", "1", "1", "1", "2", "2", "2", "3", "3", "4", "5", "5", "6", "7", "7", "8", "9", "9", "10", "10", "11", "11", "12", "12", "10", "10", "10", "11", "11", "11", "11", "13", "13", "13", "11", "11", "11", "11", "13", "13", "12", "14", "13", "15", "15", "15", "16", "16", "17", "18", "NA", "NA", "NA", "NA", "16", "11", "15", "16", "17", "11", "11", "13", "13", "7", "12", "8", "9", "13", "6", "13", "10", "3", "4", "11", "5", "11", "15", "16", "0"

    )
)

#> 2009 ----

recoding_educ_2009 <- data.frame(
    old_value = c("No schooling",
                  "Grade R/0",
                  "Grade 1/ Sub A/Class 1",
                  "Grade 2 / Sub B/Class 2",
                  "Grade 3/Standard 1/ ABET 1(Kha Ri Gude, Sanli)",
                  "Grade 4/ Standard 2",
                  "Grade 5/ Standard 3/ ABET 2",
                  "Grade 6/Standard 4",
                  "Grade 7/Standard 5/ ABET 3",
                  "Grade 8/Standard 6/Form 1",
                  "Grade 9/Standard 7/Form 2/ ABET 4",
                  "Grade 10/ Standard 8/ Form 3",
                  "Grade 11/ Standard 9/ Form 4",
                  "Grade 12/Standard 10/Form 5/Matric (Exemption *)",
                  "Grade 12/Standard 10/Form 5/Matric (No Exemption",
                  "NTC 1/ N1/NC (V) Level 2",
                  "NTC 2/ N2/ NC (V) Level 3",
                  "NTC 3/ N3/NC (V)/Level 4",
                  "N4/NTC 4",
                  "N5/NTC 5",
                  "N6/NTC 6",
                  "Diploma with less than Grade 12/Std 10",
                  "Certificate with less than Grade 12/Std 10",
                  "Certificate with Grade 12/Std 10",
                  "Diploma with Grade 12/Std 10",
                  "Bachelors Degree",
                  "Bachelors Degree and post-graduate diploma",
                  "Honours Degree",
                  "Higher Diploma (Technikon/University of Technology)",
                  "Post Higher Diploma (Technikon/University of Technology Masters, Doctoral)",
                  "Doctoral Degrees (Doctoral Diploma and PhD)-NQF Level 10",
                  "Higher degree (Masters, Doctorate)",
                  "Other",
                  "Do not know",
                  "Unspecified"),
    new_value = c("0",
                  "0",
                  "1",
                  "2",
                  "3",
                  "4",
                  "5",
                  "6",
                  "7",
                  "8",
                  "9",
                  "10",
                  "11",
                  "12",
                  "12",
                  "10",
                  "11",
                  "11",
                  "13",
                  "13",
                  "13",
                  "11",
                  "11",
                  "13",
                  "13",
                  "15",
                  "16",
                  "16",
                  "13",
                  "15",
                  "18",
                  "17",
                  "NA",
                  "NA",
                  "NA"

    )
)

#> 2010 ----
recoding_educ_2010 <- data.frame(
    old_value = c("No schooling",
                  "Grade R/0",
                  "Grade 1/ Sub A/Class 1",
                  "Grade 2 / Sub B/Class 2",
                  "Grade 3/Standard 1/ ABET 1(Kha Ri Gude, Sanli)",
                  "Grade 4/ Standard 2",
                  "Grade 5/ Standard 3/ ABET 2",
                  "Grade 6/Standard 4",
                  "Grade 7/Standard 5/ ABET 3",
                  "Grade 8/Standard 6/Form 1",
                  "Grade 9/Standard 7/Form 2/ ABET 4",
                  "Grade 10/ Standard 8/ Form 3",
                  "Grade 11/ Standard 9/ Form 4",
                  "Grade 12/Standard 10/Form 5/Matric (Exemption *)",
                  "Grade 12/Standard 10/Form 5/Matric (No Exemption",
                  "NTC 1/ N1/NC (V) Level 2",
                  "NTC 2/ N2/ NC (V) Level 3",
                  "NTC 3/ N3/NC (V)/Level 4",
                  "N4/NTC 4",
                  "N5/NTC 5",
                  "N6/NTC 6",
                  "Diploma with less than Grade 12/Std 10",
                  "Certificate with less than Grade 12/Std 10",
                  "Certificate with Grade 12/Std 10",
                  "Diploma with Grade 12/Std 10",
                  "Bachelors Degree",
                  "Bachelors Degree and post-graduate diploma",
                  "Honours Degree",
                  "Higher Diploma (Technikon/University of Technology)",
                  "Post Higher Diploma (Technikon/University of Technology Masters, Doctoral)",
                  "Doctoral Degrees (Doctoral Diploma and PhD)-NQF Level 10",
                  "Higher degree (Masters, Doctorate)",
                  "Other",
                  "Do not know",
                  "Unspecified"),
    new_value = c("0",
                  "0",
                  "1",
                  "2",
                  "3",
                  "4",
                  "5",
                  "6",
                  "7",
                  "8",
                  "9",
                  "10",
                  "11",
                  "12",
                  "12",
                  "10",
                  "11",
                  "11",
                  "13",
                  "13",
                  "13",
                  "11",
                  "11",
                  "13",
                  "13",
                  "15",
                  "16",
                  "16",
                  "13",
                  "15",
                  "18",
                  "17",
                  "NA",
                  "NA",
                  "NA")
)

#> 2011 ----
recoding_educ_2011 <- data.frame(
    old_value = c("NTC 3/ N3/NC (V)/Level 4", "Grade 9/Standard 7/Form 2/AET 4", "Grade 6/Standard 4", "Grade 2/Sub B/Class 2", "N6/NTC 6", "Grade 12/Standard 10/Form 5/Matric (No Exemption)", "Grade 8/Standard 6/Form 1", "Diploma with Grade 12/Std 10", "Grade 11/Standard 9/ Form 4", "Bachelor's Degree and post-graduate diploma", "No schooling", "Grade 5/Standard 3/AET 2", "Grade 10/Standard 8/ Form 3", "Grade 4/Standard 2", "Grade 7/Standard 5/AET 3", "Grade 3/Standard 1/AET 1(Kha Ri Gude, Sanli)", "Bachelor's Degree", "Higher Diploma (Technikon/University of Technology)", "Grade 12/Standard 10/Form 5/Matric (Exemption *)", "Do not know", "Diploma with less than Grade 12/Std 10", "Grade 1/Sub A/Class 1", "Certificate with less than Grade 12/Std 10", "Certificate with Grade 12/Std 10", "NTC 1 N1/NC (V) Level 2", "Unspecified", "Post Higher Diploma (Technikon/University of Technology Masters, Doctoral)", "Other (specify in the box below)", "Honours Degree", "N4/NTC 4", "Higher degree (Masters, Doctorate)", "Grade R/0", "NTC 2/N2/ NC (V) Level 3", "N5/NTC 5", "Grade 5/ Standard 3/ABET 2", "Grade 9/Standard 7/Form 2/ABET 4", "Grade 4/ Standard 2", "Bachelors Degree", "Grade 3/Standard 1/ABET 1(Kha Ri Gude; Sanli)", "Grade 2 / Sub B/Class 2", "Grade 10/ Standard 8/ Form 3", "Grade 7/Standard 5/ABET 3", "Grade 11/ Standard 9/ Form 4", "NTC 1/ N1/NC (V) Level 2", "Bachelors Degree and post-graduate diploma", "Grade 1/ Sub A/Class 1", "Post Higher Diploma (Technikon/University of Technology Masters; Doctoral)", "Higher degree (Masters; Doctorate)", "NTC 2/ N2/ NC (V) Level 3", "Other"),
    new_value = c("11", "9", "6", "2", "13", "12", "8", "13", "11", "16", "0", "5", "10", "4", "7", "3", "15", "15", "12", "NA", "11", "1", "11", "13", "10", "NA", "17", "NA", "16", "13", "17", "0", "11", "13", "5", "9", "4", "15", "3", "2", "10", "7", "11", "10", "16", "1", "17", "18", "11", "NA")
)

##CHECK THE 2006-2011 EDUCTAION LEVELS. DO THEY MATCH UP?

#> 2012 ----
recoding_educ_2012 <- data.frame(
    old_value = c("NTC 3/ N3/NC (V)/Level 4", "Grade 9/Standard 7/Form 2/AET 4", "Grade 6/Standard 4", "Grade 2/Sub B/Class 2", "N6/NTC 6", "Grade 12/Standard 10/Form 5/Matric (No Exemption)", "Grade 8/Standard 6/Form 1", "Diploma with Grade 12/Std 10", "Grade 11/Standard 9/ Form 4", "Bachelor's Degree and post-graduate diploma", "No schooling", "Grade 5/Standard 3/AET 2", "Grade 10/Standard 8/ Form 3", "Grade 4/Standard 2", "Grade 7/Standard 5/AET 3", "Grade 3/Standard 1/AET 1(Kha Ri Gude, Sanli)", "Bachelor's Degree", "Higher Diploma (Technikon/University of Technology)", "Grade 12/Standard 10/Form 5/Matric (Exemption *)", "Do not know", "Diploma with less than Grade 12/Std 10", "Grade 1/Sub A/Class 1", "Certificate with less than Grade 12/Std 10", "Certificate with Grade 12/Std 10", "NTC 1 N1/NC (V) Level 2", "Unspecified", "Post Higher Diploma (Technikon/University of Technology Masters, Doctoral)", "Other (specify in the box below)", "Honours Degree", "N4/NTC 4", "Higher degree (Masters, Doctorate)", "Grade R/0", "NTC 2/N2/ NC (V) Level 3", "N5/NTC 5", "Grade 5/ Standard 3/ABET 2", "Grade 9/Standard 7/Form 2/ABET 4", "Grade 4/ Standard 2", "Bachelors Degree", "Grade 3/Standard 1/ABET 1(Kha Ri Gude; Sanli)", "Grade 2 / Sub B/Class 2", "Grade 10/ Standard 8/ Form 3", "Grade 7/Standard 5/ABET 3", "Grade 11/ Standard 9/ Form 4", "NTC 1/ N1/NC (V) Level 2", "Bachelors Degree and post-graduate diploma", "Grade 1/ Sub A/Class 1", "Post Higher Diploma (Technikon/University of Technology Masters; Doctoral)", "Higher degree (Masters; Doctorate)", "NTC 2/ N2/ NC (V) Level 3", "Other"),
    new_value = c("11", "9", "6", "2", "13", "12", "8", "13", "11", "16", "0", "5", "10", "4", "7", "3", "15", "15", "12", "0", "11", "1", "11", "13", "10", "0", "17", "0", "16", "13", "17", "0", "11", "13", "5", "9", "4", "15", "3", "2", "10", "7", "11", "10", "16", "1", "17", "18", "11", "NA"
    )
)

#> 2013 ----

recoding_educ_2013 <- data.frame(
    old_value = c("NTC 3/ N3/NC (V)/Level 4", "Grade 9/Standard 7/Form 2/AET 4", "Grade 6/Standard 4", "Grade 2/Sub B/Class 2", "N6/NTC 6", "Grade 12/Standard 10/Form 5/Matric (No Exemption)", "Grade 8/Standard 6/Form 1", "Diploma with Grade 12/Std 10", "Grade 11/Standard 9/ Form 4", "Bachelor's Degree and post-graduate diploma", "No schooling", "Grade 5/Standard 3/AET 2", "Grade 10/Standard 8/ Form 3", "Grade 4/Standard 2", "Grade 7/Standard 5/AET 3", "Grade 3/Standard 1/AET 1(Kha Ri Gude, Sanli)", "Bachelor's Degree", "Higher Diploma (Technikon/University of Technology)", "Grade 12/Standard 10/Form 5/Matric (Exemption *)", "Do not know", "Diploma with less than Grade 12/Std 10", "Grade 1/Sub A/Class 1", "Certificate with less than Grade 12/Std 10", "Certificate with Grade 12/Std 10", "NTC 1 N1/NC (V) Level 2", "Unspecified", "Post Higher Diploma (Technikon/University of Technology Masters, Doctoral)", "Other (specify in the box below)", "Honours Degree", "N4/NTC 4", "Higher degree (Masters, Doctorate)", "Grade R/0", "NTC 2/N2/ NC (V) Level 3", "N5/NTC 5"),
    new_value = c("11", "9", "6", "2", "13", "12", "8", "13", "11", "16", "0", "5", "10", "4", "7", "3", "15", "15", "12", "0", "11", "1", "11", "13", "10", "0", "17", "0", "16", "13", "17", "0", "11", "13")
)
#> 2014 ----
recoding_educ_2014 <- data.frame(
    old_value = c("98", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"),
    new_value = c("0", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "12", "10", "11", "11", "13", "13", "13", "11", "11", "13", "13", "15", "17", "15", "16", "16", "17", "NA", "NA")
)

#> 2015 ----
recoding_educ_2015 <- data.frame(
    old_value = c("98", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"),
    new_value = c("0", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "12", "10", "11", "11", "13", "13", "13", "11", "11", "13", "13", "15", "17", "15", "16", "16", "17", "NA", "NA")
)
#> 2016 ----
recoding_educ_2016 <- data.frame(
    old_value = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "98", "99"),
    new_value = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "12", "10", "11", "11", "13", "13", "13", "11", "11", "13", "13", "13", "15", "15", "15", "16", "17", "NA", "NA", "0", "NA")
)
#> 2017 ----
recoding_educ_2017 <- data.frame(
    old_value = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "98", "99"),
    new_value = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "10", "11", "11", "13", "13", "13", "11", "11", "13", "13", "15", "17", "15", "16", "18", "NA", "NA", "0", "NA")
)
#> 2018 ----
recoding_educ_2018 <- data.frame(
    old_value = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "98", "99"),
    new_value = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "10", "11", "11", "13", "13", "13", "11", "11", "13", "13", "15", "17", "15", "16", "18", "NA", "NA", "0", "NA")
)
#> 2019 ----
recoding_educ_2019 <- data.frame(
    old_value = c("NTC 3/ N3/NC (V)/Level 4", "Grade 9/Standard 7/Form 2/AET 4", "Grade 6/Standard 4", "Grade 2/Sub B/Class 2", "N6/NTC 6", "Grade 12/Standard 10/Form 5/Matric (No Exemption)", "Grade 8/Standard 6/Form 1", "Diploma with Grade 12/Std 10", "Grade 11/Standard 9/ Form 4", "Bachelor's Degree and post-graduate diploma", "No schooling", "Grade 5/Standard 3/AET 2", "Grade 10/Standard 8/ Form 3", "Grade 4/Standard 2", "Grade 7/Standard 5/AET 3", "Grade 3/Standard 1/AET 1(Kha Ri Gude, Sanli)", "Bachelor's Degree", "Higher Diploma (Technikon/University of Technology)", "Grade 12/Standard 10/Form 5/Matric (Exemption *)", "Do not know", "Diploma with less than Grade 12/Std 10", "Grade 1/Sub A/Class 1", "Certificate with less than Grade 12/Std 10", "Certificate with Grade 12/Std 10", "NTC 1 N1/NC (V) Level 2", "Unspecified", "Post Higher Diploma (Technikon/University of Technology Masters, Doctoral)", "Other (specify in the box below)", "Honours Degree", "N4/NTC 4", "Higher degree (Masters, Doctorate)", "Grade R/0", "NTC 2/N2/ NC (V) Level 3", "N5/NTC 5", "Grade 5/ Standard 3/ABET 2", "Grade 9/Standard 7/Form 2/ABET 4", "Grade 4/ Standard 2", "Bachelors Degree", "Grade 3/Standard 1/ABET 1(Kha Ri Gude; Sanli)", "Grade 2 / Sub B/Class 2", "Grade 10/ Standard 8/ Form 3", "Grade 7/Standard 5/ABET 3", "Grade 11/ Standard 9/ Form 4", "NTC 1/ N1/NC (V) Level 2", "Bachelors Degree and post-graduate diploma", "Grade 1/ Sub A/Class 1", "Post Higher Diploma (Technikon/University of Technology Masters; Doctoral)", "Higher degree (Masters; Doctorate)", "NTC 2/ N2/ NC (V) Level 3", "Other", "Grade 10/Standard 8/Form 3/NCV Level 2/Occupational Certificate – NQF Level 2", "Grade 7/Standard 5/ABET/AET 3", "Grade 12/Standard 10/Form 5/National Senior Certificate/Matric/ NCV Level 4/Occupational Certificate – NQF Level 4", "Grade 9/Standard 7/Form 2/ABET/AET 4/NCV Level 1/Occupational Certificate – NQF Level 1", "Bachelor’s Degree/Occupational Certificate – NQF Level 7", "N6/NTC 6/Occupational Certificate – NQF Level 5", "NTC lll/N3/NQF 3", "Grade 11/Standard 9/Form 4/NCV Level 3/Occupational Certificate – NQF Level 3", "NTC l/N1/NQF 1", "Grade 5/Standard 3/ABET/AET 2", "Diploma with Grade 12/Standard 10/Occupational Certificate – NQF Level 6", "Honours Degree/Postgraduate Diploma/Occupational Certificate – NQF Level 8", "N4/NTC 4/Occupational Certificate – NQF Level 5", "Certificate with less than Grade 12/Standard 10", "Grade 3/Standard 1/ABET/AET 1", "DO NOT KNOW", "Higher/National/Advance certificate with Grade 12/Std 10/Occupational Certificate – NQF Level 5", "Higher Diploma/Occupational Certificate (B-Tech Diploma) – NQF Level 7", "Post Higher Diploma (M-Tech and Master's Degree) – NQF Level 9", "Diploma with less than Grade 12/Standard 10", "N5/NTC 5/Occupational Certificate – NQF Level 5", "NTC ll/N2/NQF 2", "Doctoral Degrees (D-Tech and PhD) – NQF Level 10"),
    new_value = c(11, 9, 6, 2, 13, 12, 8, 13, 11, 16, 0, 5, 10, 4, 7, 3, 15, 15, 12, NA, 11, 1, 11, 13, 10, NA, 17, NA, 16, 18, 0, 11, 11, 5, 9, 4, 15, 3, 2, 10, 7, 11, 10, 16, 1, 17, 18, 11, NA, 10, 7, 12, 9, 15, 13, 11, 11, 10, 13, 16, 13, 11, 3, NA, 13, 15, 17, 11, 13, 11, 18)
)
#> 2020 ----
recoding_educ_2020 <- data.frame(
    old_value = c(),
    new_value = c()
)
#> 2021 ----
recoding_educ_2021 <- data.frame(
    old_value = c(),
    new_value = c()
)
